---
  - hosts: all
    sudo: yes

    tasks:
    - name: install later kernel
      apt: name="{{ item }}" state=present update_cache=yes
      with_items:
      - linux-image-generic-lts-xenial
      - linux-headers-generic-lts-xenial
      notify: restart machine

    - name: install language pack
      apt: name=language-pack-fi state=present

    - name: install icommands
      apt: deb=ftp://ftp.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-icommands-4.1.9-ubuntu14-x86_64.deb state=present

    - name: install cifs-utils
      apt: name=cifs-utils state=present

    - name: create .irodsEnv configuration directory
      file: path=/home/vagrant/.irods state=directory owner=vagrant group=vagrant

    handlers:
      - name: restart machine
        command: shutdown -P now "Ansible kernel updates triggered"
        async: 0
        poll: 0
        ignore_errors: true
